services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  web:
    build:
      context: .
    command: /opt/venv/bin/python manage.py runserver 0.0.0.0:7999 --noreload --skip-checks
    env_file:
      - ./.env
    environment:
      RUN_DJANGO_COMMANDS: "true"
      UV_PROJECT_ENVIRONMENT: /opt/venv
      UV_LINK_MODE: copy
    ports:
      - "7999:7999"
    volumes:
      - db_data:/data
    depends_on:
      - redis
  worker:
    build:
      context: .
    command: /opt/venv/bin/celery -A core worker -l info
    env_file:
      - ./.env
    environment:
      UV_PROJECT_ENVIRONMENT: /opt/venv
      UV_LINK_MODE: copy
    volumes:
      - db_data:/data
    depends_on:
      - redis

volumes:
  redis_data:
  db_data:
